# Tomcatport
server:
  port: 8080
spring:
  #Spring Batch
  batch:
    job:
      enabled: false
  # MySQL DB
  datasource:
    url: jdbc:mysql://localhost:3306/lqp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 6yhn7ujm
    driver-class-name: com.mysql.jdbc.Driver
  #database pool
   tomcat:
     max-idle: 15
     max-wait: 1000
     maxActive: 50
     min-idle: 5
     initial-size: 10
     validation-query: SELECT1
     test-on-borrow: false
     test-while-idle: true
     time-between-eviction-runs-millis: 18800
     jdbc-interceptors: ConnectionState;SlowQueryReport(threshold: 0)
# log config
logging:
  config: file:./src/main/resources/log.xml



